services:
  to-do:
    build: .
    env_file:
      - .env
    environment:
      # Overwrite the default value of POSTGRES_HOST
      # with the value of the service name as
      # Docker Compose will resolve the service name
      - POSTGRES_HOST=db
    deploy:
      replicas: 2
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env